### ISSUE TITLE
Support for polymorphic relationships

### ISSUE THREAD

**Issue by isBatak** [infinum/datx#103]
Submitting a:

* [ ] Bug report
* [x] Feature suggestion
* [ ] Support request

--------------

We should think about supporting polymorphic relationships as it is a common backend concept.
Some rails gems already support it:
- https://graphiti-api.github.io/graphiti/guides/concepts/resources#polymorphic-resources
- https://github.com/Netflix/fast_jsonapi#customizable-options

That could potentially solve the issue where we had to make an arbitrary Resource model just for showing other two different Resources in the same list and updating them through relationship.

**Comment by DarkoKukovec** [comment]
Implemented in the new buckets. Will be part of the v2
