### ISSUE TITLE
Dynamic relation type?

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#111]
Hello, first of all I want to thank you for great library which I hope I find earlier :-)

I am using `datx-jsonapi` and now I am stuck with following issue:

I am trying to consume our "timeline" of news (News models) where each of them has one-to-one relation to related model. Related model can be type of "BlogArticle" or "Advertisement" or few others types.

**Data structure**

```
**News**:
  attributes: {
    id: 1,
    type: "news",
    related_id: 21,    // ID of related model
    related_type: "blog_articles",    // or "advertisements"
  },
  // related model is also defined in JSON relations
  relationships: {
    related: {
      data: {
        id: 21,
        type: "blog_articles"
      }
    }
  }

```

```
BlogArticle: {
  attributes: {
    id: 21,
    type: "blog_articles",
    ...resource specific attributes
  }
}
```

```
Advertisement: {
  attributes: {
    id: 31,
    type: "advertisements"
    ...resource specific attributes
  }
}
```

> News.relationships.related = is always one-to-one relation

**Question & Expected behavior**

How should I define this kind of relation to be able to call `News.related` and get BlogArticle model or Advertisement model based on "related.type" relationships value.

Is there any way how to solve it with this lib?

**Comment by DarkoKukovec** [comment]
Hi @svobik7,

There is no out of the box solution for this yet (we're planning support for polymorphic relationships in a future version - #103), but I think it would work in your case if you don't define the relationship in the model and instead let the lib create the relationship dynamically during the model creation.

**Comment by svobik7** [comment]
Hi @DarkoKukovec,

thank you for quick reply. And sorry for duplicated issue.

I solved it in exact way you are talking about. So the solution for me in this time was to adapt News model constructor as follows:

```
constructor(rawData: IRawModel | IRecord = {}, collection?: PureCollection) {
    super(rawData, collection);

    initModelRef(this, 'related',
      {
        model: this.related_type, 
        type: ReferenceType.TO_ONE
      },
      this.related_id
    );
  }
```

**Comment by DarkoKukovec** [comment]
Did you try it without the constructor? `datx-jsonapi` should to this automatically when it encounters a reference that was not declared before.

**Comment by svobik7** [comment]
I see, you are right. `datx-jsonapi` init ref automatically. Great!
