### ISSUE TITLE
Example of making components "reactive" on Datx collection changes?

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#112]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

Is there any way how to make component observing and reacting to Collection/View changes directly? As normal MobX store does.

Currently I have to use component internal state to re-render with new/changed data. 

**Am I missing something?**

```js
@inject('storeResources')
@observer
class Page extends Component<{ storeResources: IJsonapiCollection }, { timestamp: number }> {
  state = {
    timestamp: 0
  };

  componentDidMount() {
   this.props.storeResources.fetchAll(News).then(() => this.doTrack());
  }

  doTrack = () => {
    this.setState({
      timestamp: Date.now()
    });
  };

  onClick = (model: News) => {
    model.title = `NEW TITLE ${Date.now()}`;
    this.doTrack();
  };

  render = () => {
   const models = this.props.storeResources.findAll(News).slice();

    return (
      <div>
        {models.map(model => (
          <div key={model.meta.id} onClick={() => this.onClick(model)}>
            <code>{model.toString()}</code>
          </div>
        ))}
      </div>
    );
  };
}
```

```js
class News extends jsonapi(Model) {
  static type = 'news';
  static endpoint = 'news';

  @prop.defaultValue('') title: string;
}
```

```js
class StoreResources extends jsonapi(Collection) {
  public static types = [News];
}

export default new StoreResources();
```

I see that there is an issue already created #94 and discused this topic - is that mean there is now way how to make data observable directly in React?

**Comment by DarkoKukovec** [comment]
The issue #94 is unrelated to this - the goal there is to make some use cases of data loading simpler and more inline with react hooks.

In your case I see two problems that prevent the component of reacting to the observable:

First one is the usage of `.slice()` in combination with `findAll()` in render. Although it might work with slice, it is beneficial to keep the return value of findAll as an observable array (unless you plan to modify the array, which would cause some issues).

The second issue is the usage of arrow function for the render method. This seems to break the mobx `observer` decorator. Not sure why, but I'm guessing because normal methods and arrow functions are not initialised in the same way.

Working example: https://codesandbox.io/s/3rkkj23v51

**Comment by svobik7** [comment]
Understand. My "copy-paste" mistake :-) Everything works as expected without arrow functions.

Anyway I like your lib so I decide to use it in our ongoing project. So therefore I made `with-nextjs` example in my own forked branch which shows basic usage of `datx` and `Next.js 8`.

[With Nextjs example](https://github.com/svobik7/datx/tree/examples/with-nextjs)

Are there any special rules about contributing to your library with examples?

**Comment by DarkoKukovec** [comment]
Looks good. @isBatak is already using it with Next.js, so maybe he can give some feedback.

**Comment by svobik7** [comment]
That would be great. Any feedback will be appreciated 🙂

I am also finishing hooks implementation of “CRUD manager” with paginated fetcher included.

Will let you soon with my approach.

**Comment by svobik7** [comment]
Hi @DarkoKukovec, I pushed my implementation of paginated fetcher hook. 

Example can be found in my own fork:
https://github.com/svobik7/datx/tree/examples/with-nextjs-hooks/examples/with-nextjs-hooks

Actually I am using two hooks `useRemoteData` for storing View and `useRemoteFetch` to managing pagination.

If you like this approach we can add to to official `datx-jsonapi` examples.

Anyway do you know about any public (and paginated) JSON API out there, so I can connect this it (instead of using my own api which I am going to set private)?

**Comment by isBatak** [comment]
Hi @svobik7, 
you can use this API http://jsonapiplayground.reyesoft.com/

I looked at your implementation but it seems like you are not fetching data on the server side (inside getInitialProps), therefore you don't leverage all the benefits of the next.js and server-side rendering.

Here you can see that there is no data displayed on the first load.
<img width="1398" alt="server-side" src="https://user-images.githubusercontent.com/4128883/57330669-0266f880-7117-11e9-8676-ebba0220b5fb.png">
If that is intended and you don't need SSR then you can easily switch to CRA and make your life easier :)

If this wasn't intended and you want all the benefits of SSR you have few options:
1. Wait for Suspense support on SSR :)
2. Implement something similar to this [SuspenseSSR](https://github.com/trojanowski/react-apollo-hooks/blob/master/src/SuspenseSSR.tsx), which means you have to find all `fetch` calls in react tree with [getMarkupFromTree](https://github.com/trojanowski/react-apollo-hooks/blob/master/src/getMarkupFromTree.tsx), put them in the one array and resolve them with `Promise.all` inside `_app`'s `getInitialProps` only on the server-side. Then create a snapshot from the store and return it from `getInitialProps` so the store can be restored inside `_app` constructor and rest of the render phase can proceed.
3. On each page where you use `<RemoteData />` you need to perform the same API call inside `getInitialProps` for the SSR phase (so duplication of `fetchOptions` will accrue) and then if you are accessing that page directly (and triggering SSR) load that cached/serialized data from the server-side inside RemoteData and skip its fetching part, but if you make a client-side transition then do normal fetch inside `RemoteData`.
