### ISSUE TITLE
Is there any option to remove View from collection?

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#113]
Submitting a:

* [ ] Bug report
* [x] Feature suggestion
* [ ] Support request

--------------

Currently I have got two pages (next.js) where each of them use own json api View. These Views are referenced in local state of one of page components (see code below). 

When I am switching between pages new View is created and attached to main collection but old one is not removed when page is "unmounted".

It would be great to tell View to destroy itself with refs or to tell collection to destroy single view explicitly (instead of managing view refs in some other global state)

Whole repo is placed here: https://github.com/svobik7/datx/tree/examples/with-nextjs-hooks/examples/with-nextjs-hooks

Without removing the view explicitly the main collection store more and more views when switching the page. See img
<img width="1280" alt="Screenshot 2019-04-10 at 07 39 54" src="https://user-images.githubusercontent.com/761766/55854540-4b05b300-5b65-11e9-8bcd-3c8dbb340857.png">

**Comment by DarkoKukovec** [comment]
I removed the requirement where the collection had to know about all views to keep the data consistent. This means that it shouldn't matter anymore how many views you create - they will be cleaned up by the garbage collector once they're not needed anymore.

The change was published in version `0.16.0`

**Comment by svobik7** [comment]
Great! I've just tested with `0.16.0` it and can confirm that there are no "unused view refs" anymore.
