### ISSUE TITLE
Map option not working properly with relationship.

### ISSUE THREAD

**Issue by stefan-willems-beech** [infinum/datx#1143]
### Used libraries

core, jsonapi, jsonapi-angular, utils

### Library version(s)

"@datx/core": "^2.4.8",  "@datx/jsonapi": "^2.4.8", "@datx/jsonapi-angular": "^2.4.9", "@datx/utils": "^2.4.8",

### Sample API response (if relevant)

payload:
```json
{"data":{"attributes":{"retrieveAt":"2023-01-24T23:00:00.000Z"},"type":"orders","relationships":{"orderLines":{"data":null}}}}
```

response:
```json
{"jsonapi":{"version":"1.0"},"errors":[{"detail":"The field orderLines is not a supported relationship.","source":{"pointer":"\/data\/relationships"},"status":"400","title":"Non-Compliant JSON:API Document"}]}
```

### Environments with the issue

Chrome 109.0.5414.74, Ubuntu 22.04.1 LTS

### Current behavior

the map option isn't working after serialization of my defined relationship.

Order model:
```ts
@Attribute({toOneOrMany: OrderLine, map: 'order-lines'}) public orderLines: OrderLine[];
```

as shown inside the payload json above the request sends a orderLines property inside the relationships array, whereas it should be order-lines as defined inside the map.

### Expected behavior

```json
{"data":{"attributes":{"retrieveAt":"2023-01-24T23:00:00.000Z"},"type":"orders","relationships":{"order-lines":{"data":null}}}}
```

### Reproduction steps

```bash
1. Create a model with a relationship which has 2 words inside it such as orderLine.
2. Add a new value to this model (my example retrieveAt is used)
3. Send a post/patch request to the backend (Laravel) where a order-lines relation is defined.
...
```

**Comment by stefan-willems-beech** [comment]
Also not working under the following versions:
"@datx/core": "^2.4.11",
    "@datx/jsonapi": "^2.4.11",
    "@datx/jsonapi-angular": "^2.4.11",
    "@datx/utils": "^2.4.8",

**Comment by DarkoKukovec** [comment]
Hi @stefan-willems-beech 
I managed to reproduce this and will try to fix it today.

**Comment by DarkoKukovec** [comment]
Should be working now in 2.4.12

**Comment by stefan-willems-beech** [comment]
Confirmed working on v2.4.12
