### ISSUE TITLE
Ability to send empty array or no relations on model.save()

### ISSUE THREAD

**Issue by stefan-willems-beech** [infinum/datx#1146]
### Used libraries

core, jsonapi, jsonapi-angular, utils

### Library version(s)

"@datx/core": "2.4.6", "@datx/jsonapi": "2.4.6", "@datx/jsonapi-angular": "2.4.7",

### Issue description

There is a problem with JSON:API spec compliance, where sending a relationship object with a data field which is null is not compliant with the JSON:API spec which my API doesn't accept.

current payload:
```json
{
    "data": {
        "attributes": {
            "retrieve_at": "2023-01-25T23:00:00.000Z",
            "status": 1
        },
        "type": "orders",
        "relationships": {
            "orderLines": {
                "data": null
            }
        }
    }
}
```

This payload is sent when I have no orderLines on my `Order` model.
The response from the api is:

```json
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "The member data must be an array.",
            "source": {
                "pointer": "/data/relationships/orderLines/data"
            },
            "status": "400",
            "title": "Non-Compliant JSON:API Document"
        }
    ]
}
```

When i try to set an empty array on the relation within the model I get this error
```
Error: [datx exception] The model needs to be in a collection to be referenceable
    at T (index.esm.js:1:1450)
    at Order.<anonymous> (index.esm.js:1:5670)
    at Order.set [as orderLines] (index.esm.js:1:3327)
    at new Order (order.ts:30:25)
    at Object.next (concept-order-create.component.ts:67:34)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at BehaviorSubject._subscribe (BehaviorSubject.js:12:44)
    at BehaviorSubject._trySubscribe (Observable.js:37:25)
```

So my question is whether it is possible to send an empty array or no relation at all when it is empty on a post request.

**Comment by DarkoKukovec** [comment]
Hi @stefan-willems-beech 
It is, but as the error says, in order to use any relationships, the model needs to be in a collection. Also, you can use the `defaultValue` inside of the Attributes decorator to set the default value (since assigning it directly breaks things).

**Comment by stefan-willems-beech** [comment]
Hi @DarkoKukovec, 

So correct me if I am wrong, I am able to define the empty array with the `defaultValue` option.
But when I set it to the empty array it breaks the model?
Is this error more like a warning whereas I can't use the relationship array when it is empty?

My question is, is there a solution direction where I can store the model against my API?

**Comment by DarkoKukovec** [comment]
Now that you say it, I'm actually not 100% sure this will work (never tried it), but in this case you couldn't do `new OrderLine(data)`, but instead use the `collection.add(data, OrderLine)` because in this case the model will be added to the collection before the data is assigned to it. Relationships require collections because relationships only save references and they need to have a place where they can then find the exact model (and this can't work with regular js references because it wouldn't be possible to serialize them).

**Comment by stefan-willems-beech** [comment]
So, there isn't currently a way to have an empty relationship collection on a model or the ability to **not** serialize the relationship collection to json when it has no data?

**Comment by DarkoKukovec** [comment]
Those two should work fine:
Adding it to collection manually:
```ts
const order = new Order(data);
colleciton.add(order);
order.orderLines = [];
order.save();
```
Creating it within collection:
```ts
const order = collection.add(data, Order);
order.orderLines = [];
order.save();
```

**Comment by stefan-willems-beech** [comment]
I have validated the first solution (adding it to the collection manually).

Thanks for the quick response
