### ISSUE TITLE
Cannot access 'Order' before initialization 

### ISSUE THREAD

**Issue by stefan-willems-beech** [infinum/datx#1149]
### Used libraries

core, jsonapi, jsonapi-angular, utils

### Library version(s)

     "@datx/core": "^2.4.12",     "@datx/jsonapi": "^2.4.12",     "@datx/jsonapi-angular": "^2.4.12",     "@datx/utils": "^2.4.8",

### Environments with the issue

Chrome 109.0.5414.74, Ubuntu 22.04.1 LTS

### Current behavior

```ts
export class OrderLine extends BaseModel {
    static type = 'order-lines';

    @Attribute({toOne: Order}) public order: Order;
}
```

```ts
export class Order extends BaseModel {
    static type = 'orders';

    @Attribute({
        map: 'order-lines',
        toMany: OrderLine,
    }) public orderLines?: OrderLine[];
}
```

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./angular/",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "noUnusedLocals": true,
    "noUnusedParameters": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}
```

We currently want the models to know eachother, where we want to create an orderline model with the relation towards order.
Furthermore we want the Order to include the orderlines to view them inside a table.

Currently when adding the `@Attribute({toOne: Order}) public order: Order;` attribute to the `OrderLine` model, the application doesn't work and throws the error `Cannot access 'Order' before initialization`.

Without the added relation the application works.

### Expected behavior

We can define the relation both ways on the model without getting an error.

### Reproduction steps

```bash
See code above, on startup the application will fail due to not supporting relations both ways.
```

**Comment by DarkoKukovec** [comment]
Hi @stefan-willems-beech,

This is basically a case of a circular dependency. To work around, you can either  use the type string instead off a class (e.g. `toOne: 'orders'`) or a function (e.g. `toOne: () => Orders`).

**Comment by stefan-willems-beech** [comment]
Yeah thought so already, but didn't really know the options I had to solve it.

Thanks for the input.
