### ISSUE TITLE
Patch example with `undoPatch` included

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#117]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

Writing this after `applyPatch` /  `undoPatch` code digging. As there is no example it will be cool to create one. I am willing to create it (by pull request) with my approach but first of all need to clarify is I am using patches right.

I ended up with two model clones to make `undoPatch` working properly when remote request fail.

```ts
...MyModel

@prop
isFulfilled: boolean;

makeFulfilled() {
  const oldModel = this.clone() as MyModel;
  const newModel = this.clone() as MyModel;

  newModel.isFulfilled = true;

    console.log(
      'before patching',
      oldModel.isFulfilled     // false
      newModel.isFulfilled   // true
    );

    const patch = {
      patchType: PatchType.UPDATE,
      model: {
        type: oldModel.meta.type,
        id: oldModel.meta.id
      },
      oldValue: oldModel,
      newValue: newModel
  }

  this.applyPatch(patch);

  // remote action call is invoked and when fails it will apply undoPatch
  callRemoteAction().catch(() => this.undoPatch(patch))
}

...somewhere in my code
model.makeFulfilled()
```
> NOTE: model is IJsonApiModel instance attached to collection and custom view

Am I using PATCHES right? Are two model clones really needed or am I missing something?

**Comment by svobik7** [comment]
Now I found that my approach is wrong because model relations are erased after `applyPatch` is invoked.

How should I use patch properly?

**Comment by DarkoKukovec** [comment]
This will work, but a few considerations:

Old value doesn't need to contain anything that newValue doesn't. In your case, `{ isFulfilled: this.isFulfilled }` should be enough (unless `callRemoteAction` will change something).

I never really intended for manual patch generating. Not sure if better, but an alternative would be:
```typescript
...MyModel

@prop
isFulfilled: boolean;

makeFulfilled() {
  let patch;
  const removePatch = this.onPatch((_patch) => patch = _patch);
  this.isFulfilled = true;
  removePatch();

  // remote action call is invoked and when fails it will apply undoPatch
  callRemoteAction().catch(() => this.undoPatch(patch))
}

...somewhere in my code
model.makeFulfilled()
```

**Comment by svobik7** [comment]
I see, so there is no need to manual patch creation. It sounds great 👍

So it would be great to add this to examples as I did not catch from docs.

Thank you for explanation.
