### ISSUE TITLE
File upload example

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#118]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

Do anyone has working file upload example in datx model way?

Before moving to datx I was uploading files using something like:

```js
const data = new FormData();
data.append('file', file); // where file is type of File
data.append(...) // append another attrs

...then invoking multipart content type request
```

As datx is model based (which is great btw) what is the best way of uploading files within jsonapi model in my case `ImageModel`?

**Comment by isBatak** [comment]
Hi @svobik7,
{json:api} doesn't specify how to handle file uploads so we are on our own here.
I suggest that you create a separate endpoint just for upload (e.g. `example.com/upload`) where you can normally upload your files with `FrormData` and response will be a URL to the uploaded file or some arbitrary JSON response (not {json:api} related) with file metadata. 
Then you can create new `ImageModel` and fill it with data from the previous request and save it.
If you need resumable upload look at this protocol https://tus.io/

**Comment by svobik7** [comment]
Hi @isBatak, sorry for late response (we were launching our new website). I ended up with exact solution you described.

After I sent main POST request and receive response I upload images one by one on specific endpoint.
