### ISSUE TITLE
Error: [MobX] Cannot apply `@action` to `t.prototype.removeOne`

### ISSUE THREAD

**Issue by davinci2015** [infinum/datx#1180]
### Used libraries

mobx, mobx-react, datx, datx-jsonapi

### Library version(s)

datx-jsonapi ^1.1.4, datx ^1.1.4, mobx ^6.9.0, mobx-react ^7.6.0

### Environments with the issue

Node v18.12.1, React-Native v0.71.8

### Current behavior

I get the following error after updating to Mobx 6.9.0.

<img width="837" alt="Screenshot 2023-05-20 at 16 33 12" src="https://github.com/infinum/datx/assets/11479975/175cfa4a-22b0-4aee-99fd-f0602780b814">

```text
Error: [MobX] Cannot apply '@action' to 't.prototype.removeOne':
The field is already decorated with '@action'.
Re-decorating fields is not allowed.
Use '@override' decorator for methods overridden by subclass
```

There's similar issue related to another library (mobx-state-tree) https://github.com/mobxjs/mobx-state-tree/issues/1653

### Expected behavior

Mentioned error is not happening and the application is running properly.

**Comment by DarkoKukovec** [comment]
Hi @davinci2015 
MobX v6 is not supported on DatX v1. There were some signifficant changes between v5 and v6 and everything is handled in DatX v2, but since v1 was already in maintenance mode at that point, there was no point in adding the support.

**Comment by DarkoKukovec** [comment]
If you want to use the latest mobx, you'll need to update to v2.

As a minimal set of changes for this, you can check the following page in the docs: https://datx.dev/docs/migration-guide/breaking-changes

**Comment by davinci2015** [comment]
Thank you for the info and for providing links! I will close the issue.

**Comment by DarkoKukovec** [comment]
Just one additional info. If you decide to go the v1->v2 upgrade route, we have some codemods that might also help: https://datx.dev/docs/migration-guide/codemods
