### ISSUE TITLE
Circular relation between two models does not work

### ISSUE THREAD

**Issue by szymsza** [infinum/datx#1215]
### Used libraries

core

### Library version(s)

3.0.0

### Environments with the issue

Node.js 18

### Current behavior

When two models have a mutual `toOne` relation, an error occurs (`ReferenceError: Cannot access '...' before initialization`). This error can only be resolved by removing at least one of the `@Field` decorators.

### Expected behavior

Models should be able to reference each other as this is arguably a common use case.

### Reproduction steps

1. Create a `Person` model:
```ts
import { Model, Field } from '@datx/core';
import User from './user';

export default class Person extends Model {
	@Field({ toOne: User, defaultValue: null })
	public user: User | null = null;
}
```

3. Create a `User` model:
```ts
import { Model, Field } from '@datx/core';
import Person from './person';

export default class User extends Model {
	@Field({ toOne: Person, defaultValue: null })
	public person: Person | null = null;
}
```
4. Use any of the models in any way:
```ts
import Person from './person';
import { Collection } from '@datx/core';

class C extends Collection {
	static types = [Person];
}

(new C()).add({
	user: null,
}, Person);
```
5. Get a `ReferenceError: Cannot access 'Person' before initialization`. Disappears if either of the two `@Field` decorators is removed.

**Comment by DarkoKukovec** [comment]
That's due to circular dependencies issues in JS. The solution for this is to change one of them slightly, e.g.
```typescript
import { Model, Field } from '@datx/core';
import Person from './person';

export default class User extends Model {
	@Field({ toOne: () => Person, defaultValue: null }) // toOne receives a function instead of the direct value
	public person: Person | null = null;
}
```

**Comment by szymsza** [comment]
That seems to do the trick! Thank you for a very quick answer and great work on the library.
