### ISSUE TITLE
Caching revamp

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/datx#131]
Multiple caching strategies:
* No caching
* Cache while revalidate
* Prefer cache
* Custom strategies?

Multiple invalidation strategies - should support multiple network approaches (JSON API, etc.)

Cache should be serialised and should be possible to import it (hydratization)

First implementation will be JSON API specific, but the goal is to create something generic that could be used with other mixins or custom network implementations.

**Comment by DarkoKukovec** [comment]
```typescript
export enum CachingStrategy {
  NETWORK_ONLY, // Ignore cache
  NETWORK_FIRST, // Fallback to cache only on network error
  STALE_WHILE_REVALIDATE, // Use cache and update it in background
  CACHE_ONLY, // Fail if nothing in cache
  CACHE_FIRST, // Use cache if available
  STALE_AND_UPDATE, // Use cache and update response once network is complete
}
```

`STALE_AND_UPDATE` is still WIP

**Comment by isBatak** [comment]
Wow, a nice set of strategies :D 
Will it be possible to define strategy per request? 
In the case of autocomplete search, you don't want to cache anything and in the case of fetching list of posts you want STALE_WHILE_REVALIDATE strategy.

**Comment by DarkoKukovec** [comment]
Yes, right now you can define it globally and on the request level, but I also plan to allow it on the collection level. You can also define the maxAge for cache on same levels.
