### ISSUE TITLE
 self association model update data error

### ISSUE THREAD

**Issue by dzy321** [infinum/datx#148]
Submitting a:

* [x] Bug report

--------------

If this is a bug report, please provide as many as possible of the following info:

* datx version 1.0.1
* environments chrome 
* steps to reproduce
```js
const { Model, setupModel, Collection, prop } = require('datx')

const Person = setupModel(Model, {
  type: 'person',
  idAttribute: 'id',
  fields: {
    id: undefined,
    name: undefined,
    age: 0,
    owner: undefined,
  }
})
prop.toOne('person')(Person.prototype, 'owner')
Collection.types = [Person]
const collection = new Collection()

collection.add({ name: 'cat', id: 1 }, 'person')
// update
collection.add({ name: 'dog', id: 1, owner: { id: 1, name: 'dog' } }, 'person')

const persons = collection.findAll('person')

console.log(JSON.stringify(persons))
```
* current behavior
![image](https://user-images.githubusercontent.com/14145866/67194213-3b76f900-f429-11e9-95c1-855b21072eff.png)

**Comment by DarkoKukovec** [comment]
Hi @dzy321 
Is there a reason why you are using setupModel? I would strongly recommend to use the [first option](https://github.com/infinum/datx/wiki/Defining-models#option-1) of defining models.

The problem itself could be that you're passing `Person.prototype` to the `toOne` method instead of only `Person`.

Also, modifying the imported collection is ok in theory if you're using only one instance, but I would still recommend to create your own Collection that extends the datx collection instead.

**Comment by dzy321** [comment]
> first option

I follow your advice， it work fine. But i need dynamic create model，may be can not use class. 
```js
const { Model, setupModel, Collection, prop } = require('datx')

class Person extends Model {
}

Person.type = 'person'
Person.idAttribute = 'id'

// const Person = setupModel(Model, {
//   type: 'person',
//   idAttribute: 'id',
//   fields: {
//     id: undefined,
//     name: undefined,
//     age: 0,
//     owner: undefined,
//   }
// })
prop.toOne(Person)(Person, 'owner')

class MyCollection extends Collection { }

MyCollection.types = [Person]

const collection = new MyCollection()

collection.add({ name: 'cat', id: 1 }, 'person')

// Delete the next line，will be right
collection.add({ name: 'dog', id: 1, owner: { id: 1, name: 'dog' } }, 'person')

const persons = collection.findAll('person')

console.log(JSON.stringify(persons))
```

**Comment by DarkoKukovec** [comment]
ok, in that case `setupModel` makes sense (and it should work). I think the `Person.prototype` was the main issue here.

**Comment by dzy321** [comment]
> ok, in that case `setupModel` makes sense (and it should work). I think the `Person.prototype` was the main issue here.

Person.prototype replace with Person , also run error

**Comment by dzy321** [comment]
hi， class also has problem, if I use correct idAttribute 

```js
const { Model, setupModel, Collection, prop } = require('datx')

class Person extends Model {
}

Person.type = 'person'
prop.identifier(Person, 'id')
prop(Person, 'name')
prop.defaultValue(0)(Person, 'age')

prop.toOne(Person)(Person, 'owner')

class MyCollection extends Collection { }

MyCollection.types = [Person]

const collection = new MyCollection()

collection.add({ name: 'cat', id: 1 }, 'person')

// Delete the next line，will be right
collection.add({ name: 'dog', id: 1, owner: { id: 1, name: 'dog' } }, 'person')

const persons = collection.findAll('person')

console.log(JSON.stringify(persons))


```

**Comment by DarkoKukovec** [comment]
Is the issue still happening with the last example? Another thing I noticed is that you shouldn't have the `owner` field inside of `setupModel` if you're adding it as a `toOne` - if you do this, owner would at the same time be a regular property and a reference and that's why the issue happens.

**Comment by dzy321** [comment]
> Is the issue still happening with the last example? Another thing I noticed is that you shouldn't have the `owner` field inside of `setupModel` if you're adding it as a `toOne` - if you do this, owner would at the same time be a regular property and a reference and that's why the issue happens.

this issue still happening with the last example,  the key is owner id  = 1 and record.id = 1

collection.add({ name: 'dog', id: 1, owner: { id: 1, name: 'dog' } }, 'person')

**Comment by DarkoKukovec** [comment]
The issue might be that you're creating the reference from `Person` to `Person`, but when you're adding the data it is referencing itself while also having other data that will try to overwrite the other one that is also being initialized at that point.
From this context, you would probably need a `Pet` model that has the owner relationship. The other way would be to only pass the id if it's referencing itself: `collection.add({ name: 'dog', id: 1, owner: 1 }, 'person')`
