### ISSUE TITLE
Support request: Updating models and customising the PATCH request

### ISSUE THREAD

**Issue by dusandjovanovic** [infinum/datx#203]
Submitting a:

* [x] Support request

--------------

Hello, I am using `datx` together with `mobx` in a very delicate way where `mobx` stores are made generically and used on the Front-End. However, I encountered a small issue when updating items with `datx's` methods - the issue is how the resulting `PATCH` request is shaped.

```
@observable
public configResources: ConfigItemResource[];

// where ConfigItemResource is generic and extends AbstractResource
// and AbstractResource extends jsonapi(Model)

...

@action.bound 
async editResource(partialUpdate: Array<PartialResource<ConfigItemResource>>)
 // where partialUpdate is array of changes to commit to the model instance
    ...
    const itemToUpdate = this.configResources.find(...);

    partialResource.forEach((partialUpdate) => {
         itemToUpdate.assign(partialUpdate.key, partialUpdate.value);
    });

    await itemToUpdate.save();
```

So the idea is to have a `partialUpdate` array of `key/value` updates to perform. Every `key` is present on the model and `.assign()` method is used with key's `value`. After issuing `.save()` **all attributes** of that object are present in the `PATCH` request (even the ones which remained intact). 

My main question is - is it possible to **strip off the intact attributes in the `PATCH` request**? Basically, I would like only the attributes for which the `.assign()` method was called to end up in the request body. It is a backend issue at the moment (since issued `PATCH` requests should only contain a subset of model's attributes) and I could really use some help with this. One thing that came to mind is to override the model's `save()` method if possible but I couldn't find anything on that in the docs.

**Comment by DarkoKukovec** [comment]
Hi @dusandjovanovic 
Unfortunately, this is not possible in the v1 of the lib. However, this was implemented in v2 as part of #130 so it's possible to use it if you upgrade to v2. It's currently in beta, but it should be stable (basically, a release candidate).

**Comment by dusandjovanovic** [comment]
In the meantime I found a "workaround" solution, it's definitely not pretty but will get the job done until v2 is released. That solution would be stripping the model from non-relevant attributes while creating it.

`/**
     * Constructor
     * @param rawData
     * @param collection
     */
    constructor(rawData: IRawModel = {}, collection?: Collection) {
        const { somethingNotNeeded, ...other } = rawData;
        if (rawData.__META__) rawData.__META__.fields = ['key', 'value'];
        super(other, collection);

        this.doesModelHaveSomething = !!somethingNotNeeded;
    }`

**Comment by dusandjovanovic** [comment]
@DarkoKukovec I already closed the issue but just a quick follow up question. When could we expect v2 to be released? We were considering using the beta in the meantime but sadly I can't find any documentation/migration articles on it.

**Comment by DarkoKukovec** [comment]
I don't have an exact date yet because I'm still working on the new `datx-network`, but other than that, everything else is ready. We have a bug with deploying the docs (two branches with different docs versions), but you can find the latest one here: https://github.com/infinum/datx/tree/release/v2/docs

**Comment by dusandjovanovic** [comment]
Thank you, will have a look at it now.
