### ISSUE TITLE
[v2] Save fail when using bind() in model constructor

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#218]
Submitting a:

* [x] Bug report
* [ ] Feature suggestion
* [ ] Support request

--------------

When trying to update a model (previously fetched from server) I am getting `TypeError: Cannot read property 'referenceDef' of undefined`

This is because bound methods are included in `Object.keys()` but does not exists in datx fields. See below where code failes:

<img width="605" alt="Screenshot 2020-11-11 at 15 12 22" src="https://user-images.githubusercontent.com/761766/98821889-69621d80-2430-11eb-8211-ad090ea26808.png">

Method is bound in class constructor like this:

<img width="607" alt="Screenshot 2020-11-11 at 15 12 29" src="https://user-images.githubusercontent.com/761766/98821940-7979fd00-2430-11eb-888b-4a308801ef41.png">

* datx version - 2.0.0-beta.7
* datx-jsonapi version - 2.0.0-beta.7

## Steps to reproduce:
1. add class method `dummy() {}` to your json api model
2. bound this method in model constructor `this.dummy = this.dummy.bind(this)`
3. save model

**Comment by DarkoKukovec** [comment]
This fix was published in version 2.0.0-beta.8
Thanks for the contribution!
