### ISSUE TITLE
Reference returns GenericModel instead of actual model

### ISSUE THREAD

**Issue by pharmarin** [infinum/datx#228]
Submitting a:

* [X] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

If this is a bug report, please provide as many as possible of the following info:

* datx version: ^2.0.0-beta.8
* datx-jsonapi version (if used), sample API response: ^2.0.0-beta.8
* environments (browsers?, versions) where the issue happens: chrome, react-app
* environments (browsers?, versions) where the issue doesn't happen
* steps to reproduce: Model with direct references
* current behavior: Calling a direct reference on a model returns an array of GenericModel instead of the actual relationship model
* expected behavior: A model with direct references should return an instance of the model or an array of instances when calling this relationship

Btw your package is very useful, thank you.

**Comment by DarkoKukovec** [comment]
Hi @pharmarin 

This is an issue when the collection can't find the target model class during initialization. There is probably one of two reasons:

* The `@Attribute` that defines the relationship is using an invalid (non-existing) type
* The target model is not in the types array in the collection

If both of those are correct, could you please add snippets of the "source" model with this specific attribute declaration and "target" model?

**Comment by pharmarin** [comment]
Awesome ! Thank you for your rapid answer ! 😉
