### ISSUE TITLE
'extendObservabe' only accepts plain objects as second argument

### ISSUE THREAD

**Issue by pharmarin** [infinum/datx#233]
Submitting a:

* [X] Bug report
* [ ] Feature suggestion
* [X] Support request

--------------

If this is a bug report, please provide as many as possible of the following info:

* datx version : 2.0.1
* datx-jsonapi version : 2.0.0
* steps to reproduce : try to assign an array as model value (ex : user.assign('role', ['admin'])
* current behavior : an error is thrown ([MobX] 'extendObservabe' only accepts plain objects as second argument)
* expected behavior : set the value as an array

This issue did not exist in beta, but since I upgraded to 2.0.1 the error is thrown.

**Comment by DarkoKukovec** [comment]
Hi @pharmarin 

Thanks for the report! A few people already mentioned this issue to me, but this is the most specific information about steps to reproduce, so it will be very useful!

Just curious, which beta did you use before (when it worked)?

**Comment by DarkoKukovec** [comment]
I just realised this is actually related to another issue I was debugging today. Please try to update datx to 2.0.3 and check if it's still happening.

**Comment by pharmarin** [comment]
Was using beta 8 before the upgrade

**Comment by pharmarin** [comment]
Works like a charm with 2.0.4

Thank you for your reactivity !
