### ISSUE TITLE
[MobX] Extending an object with another observable (object) is not supported

### ISSUE THREAD

**Issue by svobik7** [infinum/datx#250]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [x] Support request

--------------

Hi there, I am currently facing the following mobx runtime error:

`Error: [MobX] Extending an object with another observable (object) is not supported`

This error occurred after I upgraded datx from `2.0.0-beta.8` to latest stable `2.1.0`. After a while of investigating I found out that it is caused by models which have custom autoId logic and one of their attributes is object e.g.:

```ts
const initialMembership = {
  current_plan_status: UsrMembershipStatus.None,
  current_prescription_due_at: 0,
  current_prescription_expires_at: 0,
  current_prescription_type: MembershipRole.None,
  current_prescription_price: 0,
  next_prescription_due_at: 0,
  next_prescription_expires_at: 0,
  next_prescription_type: MembershipRole.None,
  next_prescription_price: 0,
  public_type: MembershipRole.None,
}

class MeModel extends RemoteModel implements MeInterface {
  static type = RemoteModelType.Me
  static endpoint = RemoteModelEndpoint.Me

  @Attribute({ defaultValue: initialMembership })
  membership: MeInterface['membership'] = initialMembership

  constructor(data: IRawModel = {}, collection?: PureCollection) {
    super(data, collection)

    this.hasPendingMembershipRole = this.hasPendingMembershipRole.bind(this)
    this.hasActiveMembershipRole = this.hasActiveMembershipRole.bind(this)
  }

  // use custom value for fist auto id generation
  static autoIdValue = 0

  // use custom auto id generation
  static getAutoId() {
     return 0
  }

```

I am using zero autoId logic to keep only one new instance (not persisted yet) of model at a time. I older version everything works well and now I am getting above error. 

I was debugging Mobx during that error and it seems that somehow `membership` attribute is being updated with observable object instead of raw object and because of that the error is thrown.

<img width="1295" alt="Screenshot 2021-05-10 at 8 56 39" src="https://user-images.githubusercontent.com/761766/117618211-e49d5580-b16d-11eb-9de6-bd50eed399d6.png">

Once I comment out `autoIdValue` and `getAutoId` then no error is thrown and everything seems ok.

Have you ever faced similar error? Is there some way how to keep custom autoId works with latest version of datx?
Thank you

---

* datx version: 2.1.0
* datx-jsonapi version: 2.2.0
* datx-network version: 2.1.0
* datx-utils version: 2.1.0

**Comment by svobik7** [comment]
Hi @DarkoKukovec,

thank you for help. It works fine for mentioned model but for some reasons it is not working for another model `CommentModel` I have in my app.  I will investigate a bit more tomorrow and let you know.

Thank you.

**Comment by svobik7** [comment]
Hi @DarkoKukovec,

I investigated a bit more and found some strange behaviour. After upgrading to latest DatX I am not able to properly save json api model. After successful response is received from remote API datx fails to process this response with error :

```
[MobX] Extending an object with another observable (object) is not supported
```

### Simplified example I use to debug that error:

1. Model definition file:
```ts
import { Attribute, Model } from '@datx/core'
import { jsonapi } from '@datx/jsonapi'

// remote based model with observable properties
class CommentModel extends jsonapi(Model) {
  static type = 'comments'
  static endpoint = 'comments'

  @Attribute({ defaultValue: [] })
  actual_images: string[]

  @Attribute({ defaultValue: '' })
  content: string

  @Attribute({ defaultValue: 0 })
  created_at: number
}

export default CommentModel
```

2. Usage

```ts
const model = new CommentModel({
    content: 'Test comment',
    related_type: 'some_related_type',
    related_id: 1234,
})

collection.add(model)
model.save()
```

Using chrome debugger I was able to detect that error is thrown inside this function:

<img width="594" alt="Screenshot 2021-07-09 at 17 39 17" src="https://user-images.githubusercontent.com/761766/125103395-98728100-e0dc-11eb-8bfa-291ffeac736f.png">

Because of `rawData` passed to that function are not really raw but has observables attached to its properties which contains object/array (as debugger shows):

<img width="221" alt="Screenshot 2021-07-09 at 17 40 58" src="https://user-images.githubusercontent.com/761766/125103715-ee472900-e0dc-11eb-8b1e-6f9b08efa136.png">

I would say that `modelToJSON` function should return data stripped of any observables. 

Could you please check it?

**Comment by svobik7** [comment]
UPDATE: When I use custom `modelToJSON` function everything works as expected.

<img width="645" alt="Screenshot 2021-07-09 at 17 52 43" src="https://user-images.githubusercontent.com/761766/125105243-8eea1880-e0de-11eb-8719-89098c53c4d8.png">

My installed packages:

```
@datx/core@2.2.1
@datx/jsonapi@2.2.0
@datx/network@2.1.0
@datx/utils@2.2.1
mobx-react@7.2.0
mobx-utils@6.0.4
mobx@6.3.2
```

**Comment by svobik7** [comment]
Hi @DarkoKukovec ,

have you had a chance to check my investigation?

I am ready to create PR if `modelToJson` would be considered as the issue reason here.

**Comment by DarkoKukovec** [comment]
Hi @svobik7, sorry for the late reply (busy few weeks).

Yes, `modelToJson` should always return only plain js objects, so this certainly looks like a bug.

Just curious - does this happen always or only when the default value is used?

**Comment by svobik7** [comment]
Yes, even if I update my model like below the error is still thrown.

```ts
class CommentModel extends jsonapi(Model) {
  static type = 'comments'
  static endpoint = 'comments'

  @Attribute()
  actual_images: string[]

  @Attribute()
  content: string

  @Attribute()
  created_at: number
}
```

So I will create PR with updated modelToJSON.
