### ISSUE TITLE
fetchAll revamp

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/datx#34]
The option is a number of pages that should be fetched. `Infinity` to fetch all available pages.

TODO: Figure out how the response object should look in this case.

**Comment by DarkoKukovec** [comment]
An out of the box idea:
* deprecate `fetch` and `fetchAll`
* deprecate `findOne` and `findAll` (maybe?)
* add `filterByType` that behaves as `findAll`
* add `getOne` and `get` that work as `fetch` and `fetchAll`, but make use of the better caching strategies #131 
* add `query` method that would do an abstraction of `getOne`/`get` and the query builder #133

**Comment by isBatak** [comment]
Maybe we can use `One` and `Many` keywords because `All` is not true. In DB we could have 10000 items and in one request we can get a paginated response with 100 items, so we definitely get array of items but not all...

**Comment by DarkoKukovec** [comment]
Current work:
Deprecate `fetch` and `fetchAll`, implement `getOne` and `getMany` with similar behaviour, but that make heavy use of caching strategies #131
