### ISSUE TITLE
Append new relationship object to toMany relationship

### ISSUE THREAD

**Issue by tanj** [infinum/datx#347]
Submitting a:

* [ ] Bug report
* [ ] Feature suggestion
* [X] Support request

--------------

I'm trying to append a relationship object to an array, but when the object is saved the relationship loses the object. I'm sure the way I'm doing it is not the correct way, but I can't seem to find another option.

I've got `Customer` object with a `toMany` attribute `job` and I want to add a `Job` to the `job` array.

### Customer
```typescript
import { Attribute, Model } from '@datx/core';
import { jsonapiAngular } from '@datx/jsonapi-angular';
import { ICustomer } from './customer.interface';
import { Job } from './job';

export class Customer extends jsonapiAngular(Model) implements ICustomer {
    static type = 'tCustomer';
    static endpoint = 'tCustomer';

    @Attribute({ isIdentifier: true })
    public id!: string;
    @Attribute()
    public sCustomer?: string;

    @Attribute({ toMany: Job })
    job?: Job[];

}
```

### Customer component action on button
```typescript
    newJob(): void {
        let job = new Job();
        // Add job to Collection
        this.tcs.dmc.add(job);
        job.addReference('customer', this.customer, {
            model: Customer,
            type: ReferenceType.TO_ONE,
        });

        if (this.customer.job) {
            this.customer.update({ job: [...this.customer.job, job] });
            // below doesn't work
            //this.customer.job.push(job);
        }
    }
```

## What happens
When I click the button to create the new job I get a new job component as I expect. I can then fill in the form and when it submits the job gets created, but the job component disappears. If I refresh the page the job is there (having been fetched from the backend).

## What I expect to happen
The job component stays on save.

**Comment by DarkoKukovec** [comment]
Hi @tanj, what actions are done when the model is saved? Do you update the model based on the save response of the server? I had multiple issues where the server would return an unexpected save response which would then mess up the local data.

btw, `this.customer.jobs.push(job);` should also work so you don't need to use the update method.
and for the addReference part, if you define a toOne relationship in the Job model, then you can also just assign it `job.customer = this.customer`

**Comment by tanj** [comment]
The server responds to the `POST` with the job object.

## `POST`
```json
{
  "data": {
    "attributes": {
      "dtDate": "2021-07-14T16:32:06.960Z",
      "sJobNumber": "S9999"
    },
    "type": "tJob",
    "relationships": {
      "customer": { "data": { "id": "10", "type": "tCustomer" } }
    }
  }
}
```
## Server Response `201 CREATED`

```json
{
  "data": {
    "attributes": {
      "dtDate": "2021-07-14",
      "ixJob": 98,
      "sJobNumber": "S9999"
    },
    "id": "98",
    "relationships": {
      "customer": { "data": { "id": "10", "type": "tCustomer" } },
      "testsheet": { "data": [] }
    },
    "type": "tJob"
  },
  "jsonapi": { "version": "1.0" }
}
```

## `push` error
When I try and use `this.customer.job.push(job);` I get this error
![image](https://user-images.githubusercontent.com/90219/125660142-e96b3736-9279-4ea6-9edb-1e6dcba1f13a.png)

**Comment by tanj** [comment]
It seems like the data returned by `getOne` has the relationships frozen. Is this by design?

```typescript
getCustomer(ixCustomer: number | string) {
        var query: IRequestOptions = {
            queryParams: {
                include: ['job', 'locations', 'locations.sub_station'],
            },
        };
        this.tcs.dmc.getOne(Customer, ixCustomer.toString(), query).subscribe((obj) => {
            this.bsCustomer.next(obj.data);
            this.customer = obj.data;
            console.log(
                'customer.locations fetch: is frozen',
                Object.isFrozen(this.customer?.locations)
            ); // true
            console.log('customer fetch: is frozen', Object.isFrozen(this.customer)); // false
        });
    }
```

![image](https://user-images.githubusercontent.com/90219/125984671-502e6e2b-f0f0-49ed-9b48-3cbbab39109f.png)

**Comment by tanj** [comment]
ok, I think I figured it out. Looks like when mobx is disabled this frozen behavior happens. If I re-enable mobx I'm able to push to the relationships and the behavior is I expected.
