### ISSUE TITLE
mobx strict-mode error on save

### ISSUE THREAD

**Issue by re5et** [infinum/datx#69]
```
mobx.module.js:2655 Uncaught (in promise) Error: [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: ObservableObject@173.meta.jsonapiPersisted
```

We are seeing the above error when saving changes to a model.  I am not super experienced with mobx, but it seems like https://github.com/infinum/datx/blob/master/packages/datx-jsonapi/src/NetworkUtils.ts#L368 isn't marked as an action anywhere?

**Comment by DarkoKukovec** [comment]
Thanks for reporting the issue. It should be fixed in the newly published version 0.11.5
