### ISSUE TITLE
model.meta - Cannot read property of 'get' of undefined

### ISSUE THREAD

**Issue by derekcannon** [infinum/datx#75]
I am trying to loop of several models in a collection returned from `findAll` and display their `id` and `name` properties. From what I understand, you can retrieve `id` off `model.meta.id`, but for me, meta is only defined on the first model in the results. 

Here's my basic setup:

```
class Vertical extends jsonapi(Model) {
  static type = "verticals";
}

class Datastore extends jsonapi(Collection) {
  static types = [Vertical];
}
```

and the payload would look like this:
```
{
    "data": [
        {
            "id": "1",
            "type": "verticals",
            "attributes": {
                "name": "Vertical A"
            }
        },
        # etc...
     ]
}
```

My app renders with initial data, so I have a variable with the JSONAPI response, and I use the `sync` method: `this.datastore.sync(data);`

Finally, I call: `this.datastore.findAll("verticals")`, which successfully returns a list with the data I want. If I iterate through this list, I get all the data I need from the vertical, except only the first object has meta:

```
this.datastore.findAll("verticals")[0].name
> "Vertical A"

this.datastore.findAll("verticals")[0].meta.id
> "1"

this.datastore.findAll("verticals")[1].name
> "Vertical B"

this.datastore.findAll("verticals")[1].meta # ...
> Uncaught TypeError: Cannot read property 'get' of undefined
```

Is there something wrong with my setup here? Or perhaps I'm trying to access `id` in a non-standard way?

**Comment by DarkoKukovec** [comment]
Hi, yes, sorry :(
MobX 5 compatibility is my top priority and I did some work on that, but I didn't manage to solve all the issues yet (having some issues with decorators).

**Comment by derekcannon** [comment]
I pulled it down locally to try to fix it and I'm just glad to hear I wasn't the only one having difficulty with it 😆

Glad it's being worked on. I am really looking forward to adding this to my project!

**Comment by DarkoKukovec** [comment]
Hi again :)
The latest version (0.12.0) should work with MobX 5 (more specifically 5.5.0 and newer).
