### ISSUE TITLE
error thrown if no `attributes` hash

### ISSUE THREAD

**Issue by jondayton** [infinum/datx#78]
according to the jsonapi spec, the `attributes` hash is not required, but datx throws an error if it is not present

https://github.com/infinum/datx/blob/master/packages/datx-jsonapi/src/helpers/model.ts#L44

**Comment by jondayton** [comment]
Happy to put in a PR

**Comment by DarkoKukovec** [comment]
Thanks for the report. This should be fixed in the 0.12.0 release.
