### ISSUE TITLE
saveModel, decorateCollection, and `baseUrl` in datx-jsonapi

### ISSUE THREAD

**Issue by re5et** [infinum/datx#80]
I was attempting to use the `baseUrl` property on Model to define the url that requests should be sent to, which works for `fetch` and `fetchAll`, but does not work with `saveModel`, which only appears to look at `endpoint` and not `baseUrl`.  Why don't they build the url in the same way?  Is there anything I can do to achieve what I want?  My model is similar to the below:

```
import { Model } from 'datx'
import { jsonapi } from 'datx-jsonapi'

class Foo extends jsonapi(Model) {
  public static type = 'organizations'
  public static baseUrl = "https://some-url-that-is-not-config-baseUrl/organizations"
}
```

**Comment by DarkoKukovec** [comment]
Hi @re5et 
The `baseUrl` property on the model is actually not supposed to be there (it's not documented). It was left behind by mistake when moving the logic from the old lib. The `endpoint` property is what you need and it should behave the same in all situations.

**Comment by re5et** [comment]
OK, so without `baseUrl` on the model how can I use apis at different urls?  I have models that live on different services / urls.

**Comment by DarkoKukovec** [comment]
I didn't have such an use case yet, but I guess you could set the config `baseUrl` as empty string and then use the model `endpoint` properties to define the whole urls to the model.

**Comment by DarkoKukovec** [comment]
Also, `endpoint` can also be a function which is evaluated on every call, so you might be able to do some logic there if needed.

**Comment by re5et** [comment]
OK.  For anyone who comes upon this, found a way to make it work:

I ended up setting `config.baseUrl` to "/" to avoid issues with relative urls / endpoints.  If you are on a page like: `/foo/bar/baz` and have an endpoint of `api/foo`, you end up getting `/foo/bar/baz/api/foo` if you set `baseUrl` to an empty string.  Setting to "/" leaves you with "/api/foo".

For situations where I have a full url as the endpoint instead of a relative path, I am chopping the '/' from `baseUri` off the front of the url in `fetchReference`.

Not ideal but it works.
