### ISSUE TITLE
id doesn't populate on save() POST

### ISSUE THREAD

**Issue by jondayton** [infinum/datx#85]
Submitting a:

* [x] Bug report
* [ ] Feature suggestion
* [ ] Support request

--------------

If this is a bug report, please provide as many as possible of the following info:

*(delete if not a bug report)*

* datx version
0.12.0
* datx-jsonapi version (if used), sample API response
0.12.0
* environments (browsers?, versions) where the issue happens
Chrome 69
* environments (browsers?, versions) where the issue doesn't happen
* steps to reproduce
```js
user = store.add(properties, 'users')
await user.save()
```
* current behavior
```js
user.name
//=> "Fred"
user.id
//=> undefined
```
* expected behavior
```js
user.name
//=> "Fred"
user.id
//=> 30
```

**Comment by DarkoKukovec** [comment]
Hi @jondayton,

The `id` property on the model is never automatically populated - instead, if you're using the [`Model`](https://github.com/infinum/datx/wiki/Model) class, you can access `user.meta.id` to get the id (keep in mind that it will have a temporary value before you save it).
If you want a regular `id` property, you should create a computed:
```
@computed get id() {
  return this.model.id;
}
```

**Comment by jondayton** [comment]
Thanks @DarkoKukovec, I guess I would have assumed that it would use the id from the server. Are you saying if I want id to show up on a persisted model, I should do something like this?

```js
class User extends jsonapi(Model) {
  save = async () => {
    await super.save()
    if (!this.id) {
      this.assign('id', this.meta.id)
    }
    return this
  }
}
```

**Comment by DarkoKukovec** [comment]
There is no point to have the id in two places - you can use the computed way I wrote about above and that way you'll be able to use `user.id`. In your example, you're doing extra work and end up with two sources of truth, which is not ideal.

**Comment by jondayton** [comment]
In looking at this more, it seems that `id` is available with the id from the server in some of my models but not in others. I need to do some more research. Closing this issue for now.
