### ISSUE TITLE
Babel 7 decorator issues

### ISSUE THREAD

**Issue by DarkoKukovec** [infinum/datx#92]
When using Babel 7 with the new decorators plugin, the `@prop` decorators are ignored. This is also the case when using the Babel TypeScript plugin (like is the case with [Create react app 2](https://facebook.github.io/create-react-app/) and [Next.js 7](https://nextjs.org/) with the [TypeScript plugin](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript)).

Current workaround is described in the [setup guide](https://github.com/infinum/datx/wiki/Defining-models#option-1).

I'm working on a few ideas for a permanent workaround, but if you have any ideas how to address this, feel free to contact me.

**Comment by ywenc** [comment]
I'd be happy to take a look at this

**Comment by DarkoKukovec** [comment]
Fixed in https://github.com/infinum/datx/commit/d681f69634ba0f5b15a3b9fac6629cbe01886771. Further progress with Babel issues is tracked in #109
