### ISSUE TITLE
Updates to the wiki for Collection

### ISSUE THREAD

**Issue by ywenc** [infinum/datx#96]
Submitting a:

* [ ] Bug report
* [x] Feature suggestion
* [ ] Support request

--------------
Documentation missing for `getAllModels`, `filter`, `hasItem`. Update `remove` that it accepts a model as a parameter & that findAll will return all models if no type is given.

**Comment by DarkoKukovec** [comment]
Thanks for the feedback!

I've added the missing methods and details.
I've forgotten about the `getAllModels` since it's used internally, but it will probably be removed in the future as it has duplicate functionality with `findAll`.
